{% set version = "1.1.0" %}

package:
  name: requests-cache
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/requests-cache/requests_cache-{{ version }}.tar.gz
  sha256: 41b79166aa8e300cc4de982f7ab7c52af914a785160be1eda25c6e9265969a67

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - poetry
    - pip

  run:
    - python >=3.7
    - attrs >=21.2
    - cattrs >=22.2
    - itsdangerous >=2.0
    - platformdirs >=2.5
    - pyyaml >=5.4
    - requests >=2.22
    - ujson >=4.0
    - url-normalize >=1.4
    - urllib3 >=1.25.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.models
    - requests_cache.policy
    - requests_cache.serializers

about:
  home: https://github.com/requests-cache/requests-cache
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A transparent persistent cache for the requests library
  doc_url: https://requests-cache.readthedocs.io

extra:
  recipe-maintainers:
    - jwcook
    - cj-wright
